"""initial schema

Revision ID: 38475a16c3d5
Revises: 
Create Date: 2026-04-02 15:57:39.808841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38475a16c3d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.LargeBinary(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('session_type', sa.String(length=100), nullable=True),
    sa.Column('session_start', sa.String(length=10), nullable=True),
    sa.Column('kart_number', sa.Integer(), nullable=True),
    sa.Column('driver_weight_kg', sa.Float(), nullable=True),
    sa.Column('total_laps', sa.Integer(), nullable=True),
    sa.Column('clean_laps', sa.Integer(), nullable=True),
    sa.Column('best_lap_time', sa.Float(), nullable=True),
    sa.Column('average_time', sa.Float(), nullable=True),
    sa.Column('median_time', sa.Float(), nullable=True),
    sa.Column('std_dev', sa.Float(), nullable=True),
    sa.Column('consistency_pct', sa.Float(), nullable=True),
    sa.Column('top_speed_kmh', sa.Float(), nullable=True),
    sa.Column('max_lateral_g', sa.Float(), nullable=True),
    sa.Column('max_braking_g', sa.Float(), nullable=True),
    sa.Column('max_accel_g', sa.Float(), nullable=True),
    sa.Column('weather', sa.JSON(), nullable=True),
    sa.Column('coaching', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_team_user')
    )
    op.create_table('track_corners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chart_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('chart_type', sa.String(length=50), nullable=False),
    sa.Column('chart_key', sa.String(length=50), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chart_data', schema=None) as batch_op:
        batch_op.create_index('ix_chart_data_session_type_key', ['session_id', 'chart_type', 'chart_key'], unique=False)

    op.create_table('corner_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('corner_name', sa.String(length=50), nullable=False),
    sa.Column('corner_index', sa.Integer(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('corner_frac', sa.Float(), nullable=True),
    sa.Column('entry_speed', sa.Float(), nullable=True),
    sa.Column('min_speed', sa.Float(), nullable=True),
    sa.Column('exit_speed', sa.Float(), nullable=True),
    sa.Column('time_loss', sa.Float(), nullable=True),
    sa.Column('braking_point', sa.Float(), nullable=True),
    sa.Column('braking_distance', sa.Float(), nullable=True),
    sa.Column('trail_braking_depth', sa.Float(), nullable=True),
    sa.Column('root_cause', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corner_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('corner_name', sa.String(length=50), nullable=False),
    sa.Column('corner_index', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('archetype', sa.String(length=30), nullable=True),
    sa.Column('avg_time_loss', sa.Float(), nullable=True),
    sa.Column('total_time_loss', sa.Float(), nullable=True),
    sa.Column('best_min_speed', sa.Float(), nullable=True),
    sa.Column('avg_min_speed', sa.Float(), nullable=True),
    sa.Column('std_min_speed', sa.Float(), nullable=True),
    sa.Column('best_entry_speed', sa.Float(), nullable=True),
    sa.Column('best_exit_speed', sa.Float(), nullable=True),
    sa.Column('braking_spread', sa.Float(), nullable=True),
    sa.Column('dominant_root_cause', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('seconds', sa.Float(), nullable=False),
    sa.Column('is_outlier', sa.Boolean(), nullable=True),
    sa.Column('outlier_reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sector_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('sector_index', sa.Integer(), nullable=False),
    sa.Column('sector_name', sa.String(length=50), nullable=True),
    sa.Column('seconds', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('csv_compressed', sa.LargeBinary(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('telemetry',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=True),
    sa.Column('sample_index', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('elapsed_time', sa.Float(), nullable=True),
    sa.Column('distance_traveled', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('bearing', sa.Float(), nullable=True),
    sa.Column('speed_gps', sa.Float(), nullable=True),
    sa.Column('speed_calc', sa.Float(), nullable=True),
    sa.Column('lateral_acc', sa.Float(), nullable=True),
    sa.Column('longitudinal_acc', sa.Float(), nullable=True),
    sa.Column('combined_acc', sa.Float(), nullable=True),
    sa.Column('x_acc', sa.Float(), nullable=True),
    sa.Column('y_acc', sa.Float(), nullable=True),
    sa.Column('z_acc', sa.Float(), nullable=True),
    sa.Column('x_rotation', sa.Float(), nullable=True),
    sa.Column('y_rotation', sa.Float(), nullable=True),
    sa.Column('z_rotation', sa.Float(), nullable=True),
    sa.Column('lean_angle', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telemetry', schema=None) as batch_op:
        batch_op.create_index('ix_telemetry_session_lap', ['session_id', 'lap_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telemetry', schema=None) as batch_op:
        batch_op.drop_index('ix_telemetry_session_lap')

    op.drop_table('telemetry')
    op.drop_table('session_uploads')
    op.drop_table('sector_times')
    op.drop_table('laps')
    op.drop_table('corner_summaries')
    op.drop_table('corner_records')
    with op.batch_alter_table('chart_data', schema=None) as batch_op:
        batch_op.drop_index('ix_chart_data_session_type_key')

    op.drop_table('chart_data')
    op.drop_table('track_corners')
    op.drop_table('team_members')
    op.drop_table('sessions')
    op.drop_table('tracks')
    op.drop_table('teams')
    op.drop_table('users')
    # ### end Alembic commands ###
